version: '2.2'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cualquiera
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
    data: